baseURL = "http://fredcy.com/"
title = "fredcy"
copyright = "Copyright © 2020, Fred C Yankowski"
languageCode = "en-US"
theme = "indigo"

[params]
  Author = "Fred C Yankowski"
  Description = "Description of website for head meta tag"
  Subtitle = "Pondering about tech, philosophy, and flourishing"
  Avatar = "images/gort-firing-colorized.png"
  Biography = "Developing applications for edtech and blockchain in Go, Python, Elm, and PHP"
  ShowBio = true
  PermalinkText = "🔗"
  mainSections = ["posts"]

  # Contact/social-network identifiers for social icons
  EmailAddress = "fredcy@gmail.com"
  #FacebookUser = "fredcy"
  #FlickrUser = "FlickrUserName"
  GitHubUser = "fredcy"
  GitLabUser = "fredcy"
  #GlitchUser = "fredcy"
  KeybaseUser = "fredcy"
  LinkedInUser = "fredcy"
  #MediumUser = "MediumUserName"
  #MicroBlogUser = "MicroBlogUserName"
  #RedditUser = "fredy"
  StackOverflowUser = "7887/fred-yankowski"
  #TumblrUser = "TumblrUserName"
  TwitterUser = "fredcy"

  # These are parameters used for indieweb identity. You should set these along
  # with the above email/social network parameters.
  [params.indieWeb]  
    EmailAddress = "fredcy@gmail.com"
    #FlickrUser = "FlickrUserName"
    GitHubUser = "fredcy"
    TwitterUser = "fredcy"
    #MicroBlogUser = "MicroBlogUserName"
    Country = "U.S.A."
    City = "Batavia"

  [params.endpoints]
    Auth = "https://indieauth.com/auth"
    Token = "https://tokens.indieauth.com/token"
    # To get webmention support, just register at webmention.io and paste the link for endpoint here.
    #Webmention = "https://webmention.io/<yourusername>/webmention"
    # To get micropub support, you'll need to install a Micropub endpoint at your site and put its link there.
    # To get an endpoint with Hugo support, use nanopub: https://github.com/dg01d/nanopub
    # It will probably require some PHP hackery though, as it's fairly basic.
    #Micropub = ""
    # To get microsub support, you can use Aperture from p3k. Either go to https://aperture.p3k.io or self-host it (it's open source!)
    #Microsub = ""